version: "3.9"
services:
  server:
    container_name: server
    build:
      context: ./kingsleague
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://psql-db:5432/kingsleague
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=3ea14367A4
    networks:
      - kingsleague
    depends_on:
      - psql-db
  psql-db:
    container_name: psql-db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "kingsleague"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "3ea14367A4"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - kingsleague

networks:
  kingsleague:
    name: kingsleague
    driver: bridge

volumes:
  postgres-db:
    driver: local
