/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.5/userguide/building_swift_projects.html in the Gradle documentation.
 */

rootProject.name = "Kings League"
include("common")
include("organizer-service")
include("tournament-service")
include("match-service")
include("round-service")
include("matchDay-service")
include("team-service")
include("matchStats-service")