spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AhmedEnnaime/kingsLeagueConfig.git
          skipSslValidation: true
          clone-on-start: true
          default-label: master
#          search-paths:
#            - '{application}'

server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"
