spring:
  application:
    name: user-service
  datasource:
    url: "jdbc:postgresql://localhost:5432/user_db"
    username: "postgres"
    password: "3ea14367A4"
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
    graphql:
      graphiql:
        enabled: true
server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
