version: "3.9"
services:
  team-service:
    container_name: team-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://team-db:5432/team_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - team-db
    networks:
      - kingsLeague

  team-db:
    container_name: team-db
    image: "postgres:15"
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: "team_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - team-db:/var/lib/postgresql/data
    networks:
      - kingsLeague

networks:
  kingsLeague:
    external: true

volumes:
  team-db:
    driver: local