def projectDir = "../KingsLeague"

pipeline {
    environment { 
        registry = "ahmedennaime/kingsleague_team-service" 
        registryCredential = 'DOCKER_CRED' 
        dockerImage = '' 
    }
    agent any
    stages {
        stage("Clone project") {
            steps {
                git branch: 'master', url: 'https://github.com/AhmedEnnaime/KingsLeague.git'
            }
        }

        stage("Build project without test") {
            steps {
                dir(projectDir) {
                    sh './gradlew build -x test'
                }
            }
        }
        
        stage("Testing") {
            steps {
                dir(projectDir) {
                    sh "./gradlew :team-service:test"
                }
            }
        }
        
        stage("Publish code coverage") {
            steps {
                dir("../KingsLeague/team-service") {
                    jacoco(
                        execPattern: '**/*.exec',
                        sourcePattern: 'src/main/kotlin/com/youcode/kingsleague/team_service/services',
                        exclusionPattern: 'src/test*'
                    )
                }
                
            }
        }

        stage('Building our image') { 
            steps { 
                script { 
                    dockerImage = docker.build registry + ":$BUILD_NUMBER" 
                }
            } 
        }
        
        stage('Deploy our image') { 
            steps { 
                script { 
                    docker.withRegistry( '', registryCredential ) { 
                        dockerImage.push() 
                    }
                } 
            }
        } 
    }
}
