def projectDir = "../KingsLeague"

pipeline {
    agent any
    stages {
        stage("Clone project") {
            steps {
                git branch: 'master', url: 'https://github.com/AhmedEnnaime/KingsLeague.git'
            }
        }

        stage("Build project without test") {
            steps {
                dir(projectDir) {
                    sh './gradlew build -x test'
                }
            }
        }
        
        stage("Testing") {
            steps {
                dir(projectDir) {
                    sh "./gradlew :team-service:test"
                }
            }
        }
        
        stage("Publish code coverage") {
            steps {
                dir("../KingsLeague/team-service") {
                    jacoco(
                        execPattern: '**/*.exec',
                        sourcePattern: 'src/main/kotlin/com/youcode/kingsleague/team_service/services',
                        exclusionPattern: 'src/test*'
                    )
                }
                
            }
        }
    }
}
