pipeline {
    agent any

    stages {
        stage("Clone project") {
            steps {
                git branch: 'master', url: 'https://github.com/AhmedEnnaime/KingsLeague.git'
            }
        }

        stage("Build project with test execution") {
            steps {
                dir("../") {
                    sh "./gradlew build -x test"
                }
            }
        }
    }
}
