version: "3.9"
services:
  tournament-service:
    container_name: tournament-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tournament-db:5432/tournament_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - tournament-db
    networks:
      - kingsLeague

  tournament-db:
    container_name: tournament-db
    image: "postgres:15"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "tournament_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - tournament-db:/var/lib/postgresql/data
    networks:
      - kingsLeague

networks:
  kingsLeague:
    external: true

volumes:
  tournament-db:
    driver: local