spring:
  application:
    name: match-service
  config:
    import: optional:configserver:http://host.docker.internal:8888
  servlet:
    multipart:
      max-file-size: 1128KB
      max-request-size: 1128KB
com:
  youcode:
    kingsleague:
      storage:
        location: uploadDir

management:
  endpoints:
    web:
      exposure:
        include: "*"
