spring:
  application:
    name: tournament-service
  config:
    import: optional:configserver:http://host.docker.internal:8888

management:
  endpoints:
    web:
      exposure:
        include: "*"