version: "3.9"
services:
  config_service:
    container_name: config_service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
#    networks:
#      - kingsLeague

networks:
  default:
    external:
      name: kingsLeague