version: "3.9"
services:
  match-service:
    container_name: match-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://match-db:5432/match_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - match-db
    networks:
      - kingsLeague

  match-db:
    container_name: match-db
    image: "postgres:15"
    restart: always
    ports:
      - "5437:5437"
    environment:
      POSTGRES_DB: "match_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - match-db:/var/lib/postgresql/data
    networks:
      - kingsLeague

networks:
  kingsLeague:
    external: true

volumes:
  match-db:
    driver: local